//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp.FrequenciaWS70633
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConsoleApp.FrequenciaWS70633.IFrequenciaWS70633")]
    public interface IFrequenciaWS70633
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFrequenciaWS70633/FrequenciaDiogoMedeiros", ReplyAction="http://tempuri.org/IFrequenciaWS70633/FrequenciaDiogoMedeirosResponse")]
        int[] FrequenciaDiogoMedeiros(int[] array);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFrequenciaWS70633/FrequenciaDiogoMedeiros", ReplyAction="http://tempuri.org/IFrequenciaWS70633/FrequenciaDiogoMedeirosResponse")]
        System.Threading.Tasks.Task<int[]> FrequenciaDiogoMedeirosAsync(int[] array);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IFrequenciaWS70633Channel : ConsoleApp.FrequenciaWS70633.IFrequenciaWS70633, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class FrequenciaWS70633Client : System.ServiceModel.ClientBase<ConsoleApp.FrequenciaWS70633.IFrequenciaWS70633>, ConsoleApp.FrequenciaWS70633.IFrequenciaWS70633
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public FrequenciaWS70633Client() : 
                base(FrequenciaWS70633Client.GetDefaultBinding(), FrequenciaWS70633Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IFrequenciaWS70633.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FrequenciaWS70633Client(EndpointConfiguration endpointConfiguration) : 
                base(FrequenciaWS70633Client.GetBindingForEndpoint(endpointConfiguration), FrequenciaWS70633Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FrequenciaWS70633Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(FrequenciaWS70633Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FrequenciaWS70633Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(FrequenciaWS70633Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FrequenciaWS70633Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public int[] FrequenciaDiogoMedeiros(int[] array)
        {
            return base.Channel.FrequenciaDiogoMedeiros(array);
        }
        
        public System.Threading.Tasks.Task<int[]> FrequenciaDiogoMedeirosAsync(int[] array)
        {
            return base.Channel.FrequenciaDiogoMedeirosAsync(array);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IFrequenciaWS70633))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IFrequenciaWS70633))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:7001/FrequenciaWS70633.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return FrequenciaWS70633Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IFrequenciaWS70633);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return FrequenciaWS70633Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IFrequenciaWS70633);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IFrequenciaWS70633,
        }
    }
}
