/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Questao1JNI */

#ifndef _Included_Questao1JNI
#define _Included_Questao1JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Questao1JNI
 * Method:    rectangleArea
 * Signature: (FF)F
 */
JNIEXPORT jfloat JNICALL Java_Questao1JNI_rectangleArea
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     Questao1JNI
 * Method:    triangleArea
 * Signature: (FF)F
 */
JNIEXPORT jfloat JNICALL Java_Questao1JNI_triangleArea
  (JNIEnv *, jobject, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
