type(Key.WIN)
wait(0.1)
type("calculadora" + Key.ENTER)
wait(0.5)
num1 = input("Numero 1:")
type(num1)
op = input("Operador:")
type(op)
num2 = input("Numero 2:")
type(num2 + Key.ENTER)
wait(0.1)
type("c", Key.CTRL)