/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Calculator2JNI */

#ifndef _Included_Calculator2JNI
#define _Included_Calculator2JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Calculator2JNI
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Calculator2JNI_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Calculator2JNI
 * Method:    subtract
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Calculator2JNI_subtract
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Calculator2JNI
 * Method:    multiply
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Calculator2JNI_multiply
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Calculator2JNI
 * Method:    divide
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Calculator2JNI_divide
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
