
package webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IService {


    /**
     * 
     * @param a
     * @param b
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(operationName = "Add", action = "http://tempuri.org/IService/Add")
    @WebResult(name = "AddResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Add", targetNamespace = "http://tempuri.org/", className = "webservice.Add")
    @ResponseWrapper(localName = "AddResponse", targetNamespace = "http://tempuri.org/", className = "webservice.AddResponse")
    public Integer add(
        @WebParam(name = "a", targetNamespace = "http://tempuri.org/")
        Integer a,
        @WebParam(name = "b", targetNamespace = "http://tempuri.org/")
        Integer b);

    /**
     * 
     * @param a
     * @param b
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(operationName = "Subtract", action = "http://tempuri.org/IService/Subtract")
    @WebResult(name = "SubtractResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Subtract", targetNamespace = "http://tempuri.org/", className = "webservice.Subtract")
    @ResponseWrapper(localName = "SubtractResponse", targetNamespace = "http://tempuri.org/", className = "webservice.SubtractResponse")
    public Integer subtract(
        @WebParam(name = "a", targetNamespace = "http://tempuri.org/")
        Integer a,
        @WebParam(name = "b", targetNamespace = "http://tempuri.org/")
        Integer b);

    /**
     * 
     * @param a
     * @param b
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(operationName = "Multiply", action = "http://tempuri.org/IService/Multiply")
    @WebResult(name = "MultiplyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Multiply", targetNamespace = "http://tempuri.org/", className = "webservice.Multiply")
    @ResponseWrapper(localName = "MultiplyResponse", targetNamespace = "http://tempuri.org/", className = "webservice.MultiplyResponse")
    public Integer multiply(
        @WebParam(name = "a", targetNamespace = "http://tempuri.org/")
        Integer a,
        @WebParam(name = "b", targetNamespace = "http://tempuri.org/")
        Integer b);

    /**
     * 
     * @param a
     * @param b
     * @return
     *     returns java.lang.Float
     */
    @WebMethod(operationName = "Divide", action = "http://tempuri.org/IService/Divide")
    @WebResult(name = "DivideResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Divide", targetNamespace = "http://tempuri.org/", className = "webservice.Divide")
    @ResponseWrapper(localName = "DivideResponse", targetNamespace = "http://tempuri.org/", className = "webservice.DivideResponse")
    public Float divide(
        @WebParam(name = "a", targetNamespace = "http://tempuri.org/")
        Integer a,
        @WebParam(name = "b", targetNamespace = "http://tempuri.org/")
        Integer b);

    /**
     * 
     * @param celsius
     * @return
     *     returns java.lang.Double
     */
    @WebMethod(operationName = "CelsiusToFahrenheit", action = "http://tempuri.org/IService/CelsiusToFahrenheit")
    @WebResult(name = "CelsiusToFahrenheitResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CelsiusToFahrenheit", targetNamespace = "http://tempuri.org/", className = "webservice.CelsiusToFahrenheit")
    @ResponseWrapper(localName = "CelsiusToFahrenheitResponse", targetNamespace = "http://tempuri.org/", className = "webservice.CelsiusToFahrenheitResponse")
    public Double celsiusToFahrenheit(
        @WebParam(name = "celsius", targetNamespace = "http://tempuri.org/")
        Double celsius);

    /**
     * 
     * @param fahrenheit
     * @return
     *     returns java.lang.Double
     */
    @WebMethod(operationName = "FahrenheitToCelsius", action = "http://tempuri.org/IService/FahrenheitToCelsius")
    @WebResult(name = "FahrenheitToCelsiusResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "FahrenheitToCelsius", targetNamespace = "http://tempuri.org/", className = "webservice.FahrenheitToCelsius")
    @ResponseWrapper(localName = "FahrenheitToCelsiusResponse", targetNamespace = "http://tempuri.org/", className = "webservice.FahrenheitToCelsiusResponse")
    public Double fahrenheitToCelsius(
        @WebParam(name = "fahrenheit", targetNamespace = "http://tempuri.org/")
        Double fahrenheit);

    /**
     * 
     * @param celsius
     * @return
     *     returns java.lang.Double
     */
    @WebMethod(operationName = "CelsiusToKelvin", action = "http://tempuri.org/IService/CelsiusToKelvin")
    @WebResult(name = "CelsiusToKelvinResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CelsiusToKelvin", targetNamespace = "http://tempuri.org/", className = "webservice.CelsiusToKelvin")
    @ResponseWrapper(localName = "CelsiusToKelvinResponse", targetNamespace = "http://tempuri.org/", className = "webservice.CelsiusToKelvinResponse")
    public Double celsiusToKelvin(
        @WebParam(name = "celsius", targetNamespace = "http://tempuri.org/")
        Double celsius);

    /**
     * 
     * @param kelvin
     * @return
     *     returns java.lang.Double
     */
    @WebMethod(operationName = "KelvinToCelsius", action = "http://tempuri.org/IService/KelvinToCelsius")
    @WebResult(name = "KelvinToCelsiusResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "KelvinToCelsius", targetNamespace = "http://tempuri.org/", className = "webservice.KelvinToCelsius")
    @ResponseWrapper(localName = "KelvinToCelsiusResponse", targetNamespace = "http://tempuri.org/", className = "webservice.KelvinToCelsiusResponse")
    public Double kelvinToCelsius(
        @WebParam(name = "kelvin", targetNamespace = "http://tempuri.org/")
        Double kelvin);

    /**
     * 
     * @param numbers
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(operationName = "Max", action = "http://tempuri.org/IService/Max")
    @WebResult(name = "MaxResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Max", targetNamespace = "http://tempuri.org/", className = "webservice.Max")
    @ResponseWrapper(localName = "MaxResponse", targetNamespace = "http://tempuri.org/", className = "webservice.MaxResponse")
    public Integer max(
        @WebParam(name = "numbers", targetNamespace = "http://tempuri.org/")
        ArrayOfint numbers);

    /**
     * 
     * @param numbers
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(operationName = "Min", action = "http://tempuri.org/IService/Min")
    @WebResult(name = "MinResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Min", targetNamespace = "http://tempuri.org/", className = "webservice.Min")
    @ResponseWrapper(localName = "MinResponse", targetNamespace = "http://tempuri.org/", className = "webservice.MinResponse")
    public Integer min(
        @WebParam(name = "numbers", targetNamespace = "http://tempuri.org/")
        ArrayOfint numbers);

    /**
     * 
     * @param numbers
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(operationName = "Sum", action = "http://tempuri.org/IService/Sum")
    @WebResult(name = "SumResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Sum", targetNamespace = "http://tempuri.org/", className = "webservice.Sum")
    @ResponseWrapper(localName = "SumResponse", targetNamespace = "http://tempuri.org/", className = "webservice.SumResponse")
    public Integer sum(
        @WebParam(name = "numbers", targetNamespace = "http://tempuri.org/")
        ArrayOfint numbers);

    /**
     * 
     * @param numbers
     * @return
     *     returns java.lang.Double
     */
    @WebMethod(operationName = "Average", action = "http://tempuri.org/IService/Average")
    @WebResult(name = "AverageResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Average", targetNamespace = "http://tempuri.org/", className = "webservice.Average")
    @ResponseWrapper(localName = "AverageResponse", targetNamespace = "http://tempuri.org/", className = "webservice.AverageResponse")
    public Double average(
        @WebParam(name = "numbers", targetNamespace = "http://tempuri.org/")
        ArrayOfint numbers);

    /**
     * 
     * @param number
     * @param numbers
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(operationName = "GetIndex", action = "http://tempuri.org/IService/GetIndex")
    @WebResult(name = "GetIndexResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetIndex", targetNamespace = "http://tempuri.org/", className = "webservice.GetIndex")
    @ResponseWrapper(localName = "GetIndexResponse", targetNamespace = "http://tempuri.org/", className = "webservice.GetIndexResponse")
    public Integer getIndex(
        @WebParam(name = "numbers", targetNamespace = "http://tempuri.org/")
        ArrayOfint numbers,
        @WebParam(name = "number", targetNamespace = "http://tempuri.org/")
        Integer number);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HelloWorld", action = "http://tempuri.org/IService/HelloWorld")
    @WebResult(name = "HelloWorldResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://tempuri.org/", className = "webservice.HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://tempuri.org/", className = "webservice.HelloWorldResponse")
    public String helloWorld();

    /**
     * 
     * @param text
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Reverse", action = "http://tempuri.org/IService/Reverse")
    @WebResult(name = "ReverseResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Reverse", targetNamespace = "http://tempuri.org/", className = "webservice.Reverse")
    @ResponseWrapper(localName = "ReverseResponse", targetNamespace = "http://tempuri.org/", className = "webservice.ReverseResponse")
    public String reverse(
        @WebParam(name = "text", targetNamespace = "http://tempuri.org/")
        String text);

}
