package webservice;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.1
 * 2023-05-16T21:54:14.196+01:00
 * Generated source version: 4.0.1
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "IService")
@XmlSeeAlso({ObjectFactory.class})
public interface IService {

    @WebMethod(operationName = "CelsiusToKelvin", action = "http://tempuri.org/IService/CelsiusToKelvin")
    @Action(input = "http://tempuri.org/IService/CelsiusToKelvin", output = "http://tempuri.org/IService/CelsiusToKelvinResponse")
    @RequestWrapper(localName = "CelsiusToKelvin", targetNamespace = "http://tempuri.org/", className = "webservice.CelsiusToKelvin")
    @ResponseWrapper(localName = "CelsiusToKelvinResponse", targetNamespace = "http://tempuri.org/", className = "webservice.CelsiusToKelvinResponse")
    @WebResult(name = "CelsiusToKelvinResult", targetNamespace = "http://tempuri.org/")
    public java.lang.Double celsiusToKelvin(

        @WebParam(name = "celsius", targetNamespace = "http://tempuri.org/")
        java.lang.Double celsius
    );

    @WebMethod(operationName = "Min", action = "http://tempuri.org/IService/Min")
    @Action(input = "http://tempuri.org/IService/Min", output = "http://tempuri.org/IService/MinResponse")
    @RequestWrapper(localName = "Min", targetNamespace = "http://tempuri.org/", className = "webservice.Min")
    @ResponseWrapper(localName = "MinResponse", targetNamespace = "http://tempuri.org/", className = "webservice.MinResponse")
    @WebResult(name = "MinResult", targetNamespace = "http://tempuri.org/")
    public java.lang.Integer min(

        @WebParam(name = "numbers", targetNamespace = "http://tempuri.org/")
        webservice.ArrayOfint numbers
    );

    @WebMethod(operationName = "CelsiusToFahrenheit", action = "http://tempuri.org/IService/CelsiusToFahrenheit")
    @Action(input = "http://tempuri.org/IService/CelsiusToFahrenheit", output = "http://tempuri.org/IService/CelsiusToFahrenheitResponse")
    @RequestWrapper(localName = "CelsiusToFahrenheit", targetNamespace = "http://tempuri.org/", className = "webservice.CelsiusToFahrenheit")
    @ResponseWrapper(localName = "CelsiusToFahrenheitResponse", targetNamespace = "http://tempuri.org/", className = "webservice.CelsiusToFahrenheitResponse")
    @WebResult(name = "CelsiusToFahrenheitResult", targetNamespace = "http://tempuri.org/")
    public java.lang.Double celsiusToFahrenheit(

        @WebParam(name = "celsius", targetNamespace = "http://tempuri.org/")
        java.lang.Double celsius
    );

    @WebMethod(operationName = "Divide", action = "http://tempuri.org/IService/Divide")
    @Action(input = "http://tempuri.org/IService/Divide", output = "http://tempuri.org/IService/DivideResponse")
    @RequestWrapper(localName = "Divide", targetNamespace = "http://tempuri.org/", className = "webservice.Divide")
    @ResponseWrapper(localName = "DivideResponse", targetNamespace = "http://tempuri.org/", className = "webservice.DivideResponse")
    @WebResult(name = "DivideResult", targetNamespace = "http://tempuri.org/")
    public java.lang.Float divide(

        @WebParam(name = "a", targetNamespace = "http://tempuri.org/")
        java.lang.Integer a,
        @WebParam(name = "b", targetNamespace = "http://tempuri.org/")
        java.lang.Integer b
    );

    @WebMethod(operationName = "Multiply", action = "http://tempuri.org/IService/Multiply")
    @Action(input = "http://tempuri.org/IService/Multiply", output = "http://tempuri.org/IService/MultiplyResponse")
    @RequestWrapper(localName = "Multiply", targetNamespace = "http://tempuri.org/", className = "webservice.Multiply")
    @ResponseWrapper(localName = "MultiplyResponse", targetNamespace = "http://tempuri.org/", className = "webservice.MultiplyResponse")
    @WebResult(name = "MultiplyResult", targetNamespace = "http://tempuri.org/")
    public java.lang.Integer multiply(

        @WebParam(name = "a", targetNamespace = "http://tempuri.org/")
        java.lang.Integer a,
        @WebParam(name = "b", targetNamespace = "http://tempuri.org/")
        java.lang.Integer b
    );

    @WebMethod(operationName = "Subtract", action = "http://tempuri.org/IService/Subtract")
    @Action(input = "http://tempuri.org/IService/Subtract", output = "http://tempuri.org/IService/SubtractResponse")
    @RequestWrapper(localName = "Subtract", targetNamespace = "http://tempuri.org/", className = "webservice.Subtract")
    @ResponseWrapper(localName = "SubtractResponse", targetNamespace = "http://tempuri.org/", className = "webservice.SubtractResponse")
    @WebResult(name = "SubtractResult", targetNamespace = "http://tempuri.org/")
    public java.lang.Integer subtract(

        @WebParam(name = "a", targetNamespace = "http://tempuri.org/")
        java.lang.Integer a,
        @WebParam(name = "b", targetNamespace = "http://tempuri.org/")
        java.lang.Integer b
    );

    @WebMethod(operationName = "KelvinToCelsius", action = "http://tempuri.org/IService/KelvinToCelsius")
    @Action(input = "http://tempuri.org/IService/KelvinToCelsius", output = "http://tempuri.org/IService/KelvinToCelsiusResponse")
    @RequestWrapper(localName = "KelvinToCelsius", targetNamespace = "http://tempuri.org/", className = "webservice.KelvinToCelsius")
    @ResponseWrapper(localName = "KelvinToCelsiusResponse", targetNamespace = "http://tempuri.org/", className = "webservice.KelvinToCelsiusResponse")
    @WebResult(name = "KelvinToCelsiusResult", targetNamespace = "http://tempuri.org/")
    public java.lang.Double kelvinToCelsius(

        @WebParam(name = "kelvin", targetNamespace = "http://tempuri.org/")
        java.lang.Double kelvin
    );

    @WebMethod(operationName = "FahrenheitToCelsius", action = "http://tempuri.org/IService/FahrenheitToCelsius")
    @Action(input = "http://tempuri.org/IService/FahrenheitToCelsius", output = "http://tempuri.org/IService/FahrenheitToCelsiusResponse")
    @RequestWrapper(localName = "FahrenheitToCelsius", targetNamespace = "http://tempuri.org/", className = "webservice.FahrenheitToCelsius")
    @ResponseWrapper(localName = "FahrenheitToCelsiusResponse", targetNamespace = "http://tempuri.org/", className = "webservice.FahrenheitToCelsiusResponse")
    @WebResult(name = "FahrenheitToCelsiusResult", targetNamespace = "http://tempuri.org/")
    public java.lang.Double fahrenheitToCelsius(

        @WebParam(name = "fahrenheit", targetNamespace = "http://tempuri.org/")
        java.lang.Double fahrenheit
    );

    @WebMethod(operationName = "Add", action = "http://tempuri.org/IService/Add")
    @Action(input = "http://tempuri.org/IService/Add", output = "http://tempuri.org/IService/AddResponse")
    @RequestWrapper(localName = "Add", targetNamespace = "http://tempuri.org/", className = "webservice.Add")
    @ResponseWrapper(localName = "AddResponse", targetNamespace = "http://tempuri.org/", className = "webservice.AddResponse")
    @WebResult(name = "AddResult", targetNamespace = "http://tempuri.org/")
    public java.lang.Integer add(

        @WebParam(name = "a", targetNamespace = "http://tempuri.org/")
        java.lang.Integer a,
        @WebParam(name = "b", targetNamespace = "http://tempuri.org/")
        java.lang.Integer b
    );

    @WebMethod(operationName = "Max", action = "http://tempuri.org/IService/Max")
    @Action(input = "http://tempuri.org/IService/Max", output = "http://tempuri.org/IService/MaxResponse")
    @RequestWrapper(localName = "Max", targetNamespace = "http://tempuri.org/", className = "webservice.Max")
    @ResponseWrapper(localName = "MaxResponse", targetNamespace = "http://tempuri.org/", className = "webservice.MaxResponse")
    @WebResult(name = "MaxResult", targetNamespace = "http://tempuri.org/")
    public java.lang.Integer max(

        @WebParam(name = "numbers", targetNamespace = "http://tempuri.org/")
        webservice.ArrayOfint numbers
    );

    @WebMethod(operationName = "Reverse", action = "http://tempuri.org/IService/Reverse")
    @Action(input = "http://tempuri.org/IService/Reverse", output = "http://tempuri.org/IService/ReverseResponse")
    @RequestWrapper(localName = "Reverse", targetNamespace = "http://tempuri.org/", className = "webservice.Reverse")
    @ResponseWrapper(localName = "ReverseResponse", targetNamespace = "http://tempuri.org/", className = "webservice.ReverseResponse")
    @WebResult(name = "ReverseResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String reverse(

        @WebParam(name = "text", targetNamespace = "http://tempuri.org/")
        java.lang.String text
    );

    @WebMethod(operationName = "Sum", action = "http://tempuri.org/IService/Sum")
    @Action(input = "http://tempuri.org/IService/Sum", output = "http://tempuri.org/IService/SumResponse")
    @RequestWrapper(localName = "Sum", targetNamespace = "http://tempuri.org/", className = "webservice.Sum")
    @ResponseWrapper(localName = "SumResponse", targetNamespace = "http://tempuri.org/", className = "webservice.SumResponse")
    @WebResult(name = "SumResult", targetNamespace = "http://tempuri.org/")
    public java.lang.Integer sum(

        @WebParam(name = "numbers", targetNamespace = "http://tempuri.org/")
        webservice.ArrayOfint numbers
    );

    @WebMethod(operationName = "Average", action = "http://tempuri.org/IService/Average")
    @Action(input = "http://tempuri.org/IService/Average", output = "http://tempuri.org/IService/AverageResponse")
    @RequestWrapper(localName = "Average", targetNamespace = "http://tempuri.org/", className = "webservice.Average")
    @ResponseWrapper(localName = "AverageResponse", targetNamespace = "http://tempuri.org/", className = "webservice.AverageResponse")
    @WebResult(name = "AverageResult", targetNamespace = "http://tempuri.org/")
    public java.lang.Double average(

        @WebParam(name = "numbers", targetNamespace = "http://tempuri.org/")
        webservice.ArrayOfint numbers
    );

    @WebMethod(operationName = "GetIndex", action = "http://tempuri.org/IService/GetIndex")
    @Action(input = "http://tempuri.org/IService/GetIndex", output = "http://tempuri.org/IService/GetIndexResponse")
    @RequestWrapper(localName = "GetIndex", targetNamespace = "http://tempuri.org/", className = "webservice.GetIndex")
    @ResponseWrapper(localName = "GetIndexResponse", targetNamespace = "http://tempuri.org/", className = "webservice.GetIndexResponse")
    @WebResult(name = "GetIndexResult", targetNamespace = "http://tempuri.org/")
    public java.lang.Integer getIndex(

        @WebParam(name = "numbers", targetNamespace = "http://tempuri.org/")
        webservice.ArrayOfint numbers,
        @WebParam(name = "number", targetNamespace = "http://tempuri.org/")
        java.lang.Integer number
    );

    @WebMethod(operationName = "HelloWorld", action = "http://tempuri.org/IService/HelloWorld")
    @Action(input = "http://tempuri.org/IService/HelloWorld", output = "http://tempuri.org/IService/HelloWorldResponse")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://tempuri.org/", className = "webservice.HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://tempuri.org/", className = "webservice.HelloWorldResponse")
    @WebResult(name = "HelloWorldResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String helloWorld()
;
}
