/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class QuestaoJNI */

#ifndef _Included_QuestaoJNI
#define _Included_QuestaoJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     QuestaoJNI
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_QuestaoJNI_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     QuestaoJNI
 * Method:    subtract
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_QuestaoJNI_subtract
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
