/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Questao1JNI */

#ifndef _Included_Questao1JNI
#define _Included_Questao1JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Questao1JNI
 * Method:    finalGrade
 * Signature: (DDD)D
 */
JNIEXPORT jdouble JNICALL Java_Questao1JNI_finalGrade
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
