/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Questao2JNI */

#ifndef _Included_Questao2JNI
#define _Included_Questao2JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Questao2JNI
 * Method:    removeVowels
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Questao2JNI_removeVowels
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
