/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ShapeAreaJNI */

#ifndef _Included_ShapeAreaJNI
#define _Included_ShapeAreaJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ShapeAreaJNI
 * Method:    rectangleArea
 * Signature: (FF)F
 */
JNIEXPORT jfloat JNICALL Java_ShapeAreaJNI_rectangleArea
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     ShapeAreaJNI
 * Method:    triangleArea
 * Signature: (FF)F
 */
JNIEXPORT jfloat JNICALL Java_ShapeAreaJNI_triangleArea
  (JNIEnv *, jobject, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
