/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Questao1JNI */

#ifndef _Included_Questao1JNI
#define _Included_Questao1JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Questao1JNI
 * Method:    calculateRhythm
 * Signature: ([I[II)D
 */
JNIEXPORT jdouble JNICALL Java_Questao1JNI_calculateRhythm
  (JNIEnv *, jobject, jintArray, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
