/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ArrayMethodsJNI */

#ifndef _Included_ArrayMethodsJNI
#define _Included_ArrayMethodsJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ArrayMethodsJNI
 * Method:    max
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_ArrayMethodsJNI_max
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     ArrayMethodsJNI
 * Method:    getIndex
 * Signature: ([II)I
 */
JNIEXPORT jint JNICALL Java_ArrayMethodsJNI_getIndex
  (JNIEnv *, jobject, jintArray, jint);

/*
 * Class:     ArrayMethodsJNI
 * Method:    mean
 * Signature: ([I)F
 */
JNIEXPORT jfloat JNICALL Java_ArrayMethodsJNI_mean
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     ArrayMethodsJNI
 * Method:    reverse
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ArrayMethodsJNI_reverse
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
