/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CalculatorJNI */

#ifndef _Included_CalculatorJNI
#define _Included_CalculatorJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CalculatorJNI
 * Method:    add
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CalculatorJNI_add
  (JNIEnv *, jobject);

/*
 * Class:     CalculatorJNI
 * Method:    subtract
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CalculatorJNI_subtract
  (JNIEnv *, jobject);

/*
 * Class:     CalculatorJNI
 * Method:    multiply
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CalculatorJNI_multiply
  (JNIEnv *, jobject);

/*
 * Class:     CalculatorJNI
 * Method:    divide
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CalculatorJNI_divide
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
