/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Questao2JNI */

#ifndef _Included_Questao2JNI
#define _Included_Questao2JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Questao2JNI
 * Method:    addVAT
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_Questao2JNI_addVAT
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
