/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class RhythmCalculator */

#ifndef _Included_RhythmCalculator
#define _Included_RhythmCalculator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     RhythmCalculator
 * Method:    getRhythm
 * Signature: ([F[F)F
 */
JNIEXPORT jfloat JNICALL Java_RhythmCalculator_getRhythm
  (JNIEnv *, jobject, jfloatArray, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
