/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Questao3JNI */

#ifndef _Included_Questao3JNI
#define _Included_Questao3JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Questao3JNI
 * Method:    isPalindrome
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_Questao3JNI_isPalindrome
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
